language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry config pypi-token.pypi $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  edge: true
  on:
    tags: true
    python: 3.8
env:
  global:
  - secure: qYKWaAwXcm8Tw8SPFcn5X8GcqImO5vOKufkjQJzEH4YDMs3Wykk59z70VTXtBU4LCcJnfHNivIUh7wnUgv3MjrHPyHYk7EbXEXeq9aGZkaAkKFgmn2vXwe57qwE5hid/W1bUlhWZDXJ3Id9P7IoQXf6O4xpTGrMEEe8hnX/r8KGiDCGQNak0TXbUqkASXkpgCWEWEdcrOEz+Gec4o6d7p+AvVLvPQ4GBeoZjcgziYI9U9NQ6HVexQVPiDacFe7Hj+QlU6PwzV2eWiYzTvXQpSeJlHMnIFq42k0wAZiyxKgTTOwisPaJDJlDjALWqss/CdbUVg5muHUZuqlAwp60n2YM/EparH6DU3dJ++ElHrzDbRqwDJcDkZkA67FmGLfZd1cK8QUrUnmWbUnm+74dYkIr/a7ZX76fxpXiZ+UjVpJ3xgNhh7nkYS6sVgANFsvf8ST5S1PuAOFp2lcwjE0wKXmrrT9EAai9CQ8dEFuCwOLfEttqYmdbXvnwU1W/NZWIrZ3w2XISU5iMvbNR6LHCs3v3HNik9JxGhNf3gjB4Rf7C1BBu3DoGv4qNDphWFW3HtKJDi2iYAYNq4KgpxIhpwxUjIPU/2/FlQ/zxa9bHUVWtBu/fCRJ+Nfmt5pxgF1pvLkGS9YxJhy2KQ2LzxFGX/QHp1HDrQzOs60KltFwTMy4I=
